---
name: FBOpen
full_name: FBOpen
short_name: fbopen
type: app
owner_type: project
status: active
stage: beta
testable: true
mission: 'To aggregate and make more accessible diverse opportunities to do business with the U.S. Government'
links:
- url: https://pages.18f.gov/fbopen
  text: FBOpen API Documentation
tasks: https://github.com/18F/fbopen/issues
team:
  - github: arowla
    id: alison
    role: lead
licenses:
  fbopen:
    id: CC0
    url: https://github.com/18F/fbopen/tree/master/LICENSE.md
