language: node_js
before_install: make travis-setup
install: make npm-install
script: make test
#services: elasticsearch
#sudo: false
node_js:
    - "0.12.7"
addons:
    apt:
        packages:
            - bc
env:
  - FBOPEN_ROOT=$TRAVIS_BUILD_DIR
