name: FBOpen
url: https://18f.github.io/fbopen

markdown: kramdown
kramdown:
  use_coderay: true
  coderay_line_numbers: nil
  parse_block_html: true

pygments: true
baseurl: http://18f.github.io/fbopen
permalink: /update/:title/

welcome_message: "A set of open-source tools to help small businesses search for opportunities to work with the U.S. government."
