FORMAT: 1A
HOST: https://api.data.gov

# FBOpen API

FBOpen documentation has moved: [18F.github.io/fbopen](http://18f.github.io/fbopen/)

We've added more information and will continue to keep improving our documentation.
