# Configuration for librarian-puppet. For example:
#
forge "http://forge.puppetlabs.com"

mod "puppetlabs/vcsrepo"
mod "puppetlabs/stdlib"
mod "puppetlabs/nodejs"
mod "maestrodev/puppet-wget",
    :git => "git://github.com/maestrodev/puppet-wget.git"
mod "puppetlabs/postgresql"
mod "puppetlabs/apt"
mod "saz/timezone"
mod "stankevich/python"
mod "elasticsearch/puppet-elasticsearch",
    :git => "git://github.com/elasticsearch/puppet-elasticsearch.git"
